name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 10

      - name: Install dependencies
        run: pnpm install

      - name: Install Playwright Browsers
        run: pnpm dlx playwright install chromium

      - name: 'Create env file'
        env:
          E2E_USERNAME: ${{ env.E2E_USERNAME }}
        run: |
          touch .env
          echo E2E_USERNAME=${{ env.E2E_USERNAME }} >> .env
          cat .env

      - name: log envs
        env:
          env1: ${{ env.E2E_USERNAME }}
        run: |
          echo "BETTER_AUTH_SECRET: ${{ env.env1 }}"

      - name: Run Playwright tests
        env:
          E2E_USERNAME: ${{ env.E2E_USERNAME }}
          E2E_PASSWORD: ${{ secrets.E2E_PASSWORD }}
          E2E_HOST: ${{ env.E2E_HOST }}
          BETTER_AUTH_SECRET: ${{ secrets.BETTER_AUTH_SECRET }}
          NEXT_PUBLIC_BASE_URL: ${{ env.NEXT_PUBLIC_BASE_URL }}
          ZITADEL_API_URL: ${{ env.ZITADEL_API_URL }}
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          POSTGRES_URL: ${{ secrets.POSTGRES_URL }}
        run: pnpm run test

      - uses: actions/upload-artifact@v6
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: test-results/
          retention-days: 7